export interface Product {
  imageurl?:string,
  name?: string,
  Speciality?: string,
  Dosage?: string,
  Forme?: string,
  Presentation?: string,
  Conditionnement_primaire?: string,
  Specification?: string,
  DCI?: string,
  Classement_VEIC?: string,
  Class_Therapeutic?: string,
  Sous_Classe?: string,
  Laboratoire?: string,
  Tableau?: string,
  Duration_of_conservation?: string,
  Indication?: string,
  Generic_Princeps?: string,
  AMM?: string,
  Date_AMM?: string,
  symptome1?:string,
  symptome2?:string,
  symptome3?:string,
  prix?: string
}
